name: master-actions
run-name: RELEASE
on:
  push:
    branches:
      - master

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - name: Release tag
        id: release
        uses: RedSockActions/release_tag@v1.1.0
        with:
          token: ${{ github.token }}
          config_path: internal/config/redsock.yaml
