name: master-actions
run-name: RELEASE
on:
  push:
    branches:
      - main

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - name: Release tag
        id: release
        uses: RedSockActions/release_tag@v1.1.0
        with:
          token: ${{ github.token }}
          config_path: internal/config/redsock.yaml
    outputs:
      tag: ${{ steps.release.outputs.tag }}

  registry_release:
    runs-on: ubuntu-latest
    needs:
      - tag-release
    steps:
      - name: Release image
        if: ${{ needs.tag-release.outputs.tag != '' }}
        uses: RedSockActions/release_image@v1
        with:
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_PWD:  ${{ secrets.REGISTRY_PWD }}